### PR TITLE
update pico sdk to 1.5.1 (latest stable release)

### PR DESCRIPTION
**Pull request by maks**
This updates the pico sdk to its [`1.5.1` release](https://github.com/raspberrypi/pico-sdk/releases/tag/1.5.1).
Unfortunately git submodules only allow you to specify a specific commit sha, so if wanting to check this need to manually compare the commit for `1.5.1` with the one this PR sets for the submodule. 

Fixes: #52

### CODE REVIEW

**Comment by democloid** [comment]
@maks I'm a bit confused by this, why is the commit updating files in the submodule when it's not actually part of the repo? I would have expected it would only update a reference to the submodule commit or something.

But I have no idea about submodules, so educate me.

**Comment by maks** [comment]
> @maks I'm a bit confused by this, why is the commit updating files in the submodule when it's not actually part of the repo? I would have expected it would only update a reference to the submodule commit or something.
> 
> But I have no idea about submodules, so educate me.

@democloid yep I'm not a fan of submodules either, I've always found them non-inituitive and confusing to use! On very larger projects I've work on like the Android open src project, they have hundreds of repos and use a completely separate python tool called "repo" instead of submodules, but then that has it own problems :-) 
 
With this case, I think its just the way Github shows the changes as:
> "Submodule [pico-sdk](https://github.com/raspberrypi/pico-sdk) updated 150 files" 

but really all that should have happened in git afaik is that the reference to the commit sha for the submodule got updated to the one I chose (that is for the pico-sdk 1.5.1 release tag), 
ie. if you do this command in the top level repo
```
git submodule status
 6a7db34ff63345a7badec79ebea3aaef1712f374 sources/Externals/pico-sdk (1.5.1)
```

And that sha1 is stored as a `gitlink` per https://stackoverflow.com/a/5033973/85472.

What I actually found confusing here is that pico-sdk then has its own submodules, so I needed to recursively update them to make sure they were updated to the same commits the the pico-sdk repo has at the commit of it that I updated too. Phew! hope that makes sense?

**Comment by democloid** [comment]
It does!! thanks for the explanation

**Review by democloid — APPROVED** [review]
LGTM

**Pull request merged**
