### PR TITLE
Refactor Types.h and Variable.h

### PR DESCRIPTION
**Pull request by djdiskmachine**
Attempt to reduce RAM usage by size-limitation of strings (now max 40 characters)
Indices are now 8 bit instead of int

### CODE REVIEW

**Comment by maks** [comment]
Thanks for this PR @djdiskmachine ! 

Were you able to measure that there was a reduction in ram usage with these changes? Just looking the code, the change from `std::string` to a char array I think would actually incrase ram usage as its going from a string object that will allocate a buffer just big enough for the given string data to always allocating an array of 40 bytes irrespective of the length of the actual string data.

Given that the rp2040 has XIP (execute in place) I think the strategy needs to be to put as much as possible in flash which is plentiful vs ram. In practise this means that anywhere possible, making sure things known at compile time, such as string literals, which will go into the code image to be referred to via pointers instead of being copied at runtime into ram, which is what will happen with std::strings copy constructor for example, but also in the code in this PR using strcpy.
So in this case, instead of char arrays, I'd suggest just using `const char` pointers which are assigned to pointers to string literals, which the compiler should be placing into the binary and hence kept in flash not ram.

@democloid I think the above is correct, but you've done more work on the memory optimisation so please chime in if I got things wrong here.

**Comment by democloid** [comment]
@maks Yeah, not very convinced by this tbh. Also seems to be a bit all over the place. I agree this may increase the memory footprint.

Regardless, I'm inclined to defer any work for memory optimization until we have a good way of assessing what's the real gain from such a change. And once we have a way of doing so I'd discuss what's the best way to approach this problem, I'd probably refactor the code by type of optimization than by file or class.

**Comment by djdiskmachine** [comment]
Fair points!
If I go about it another way, how can I measure any improvement in RAM usage?
The printout after linking the executable, is this any proper indication of anything?

**Comment by democloid** [comment]
@djdiskmachine It's not easy to do right now. The printout after linking only shows static memory usage, which is not right now the majority of the memory used. This particular code is currently used in heap allocations, so hard to know. There is some rudimentary instrumentation to show how full the heap is, so in theory if you compared the heap usage at a certain point (for example after project load) of the before and after, you could see the difference. (but not the absolute maximum memory used or needed)

You can enable https://github.com/democloid/picoTracker/blob/master/sources/CMakeLists.txt#L23 in order to see memory usage as a log message.

That said, as I said before, I think we should defer these optimizations until we have better instrumentation. I'm planning on working on doing this much better.

**Comment by democloid** [comment]
I've tried a (mostly) statically compiled binary which gives me some insight into the savings in this diff and as suspected, some of the optimizations don't really render better results. I think it's probably ok to keep these (AI) ideas in mind to explore in the future, but will not merge right now as we don't have a good way to test out what works and what not. We may have a better way soon.

**Pull request closed without merging**
