### PR TITLE
Adds back "Loading" sample status when loading a project. Also shows saving a project status when you do so.

### PR DESCRIPTION
**Pull request by shockdesign**
Added missing loading sample call for project laod as was removed when adding faster import message, along with some comments to help me understand  the import and load flows. Also added a saving project message so you know it's saving. This can be removed when autosaving so it doesn't distract

### CODE REVIEW

**Review by maks — APPROVED** [review]
LGTM. message shows again when loading project 👍🏻  though I cant really see the project save dialog because at least with the projects I tested with saving is too fast 😄

**Review by democloid — CHANGES_REQUESTED** [review]
This worked in the past and was broken by a previous PR. A couple of suggestions in these situations:
1. Please reference where this was broken, so that we can go back and check
2. A revert of the last commit that broke it is all that is needed to fix it back. Line 118 was within the loadSample method but now it's outside. Is there a reason for this? For someone that knows the code, this unnecessary change might seem confusing.

As @maks says, the "saving project" dialog seems unnecessary as it cannot be seen. Unless we wanted (we don't) to be explicit to the user, then we should delay it for a second or whatever. No use in adding unnecessary code.

As it stands, this diff it's just a bunch of comments on the code which explains what the code does. Comments that explain what the code does are generally not very useful, the code speaks for itself. Comments should be used to explain the business logic when needed.

My suggestion is to revert the previous commit and be done with it.

**Comment by maks** [comment]
@shockdesign I would suggest best thing here would be to just stick to the original intent of putting back the original code line and only adding a comment for that one line to explain why its needed and not add all those other comments.

**Comment by shockdesign** [comment]
@democloid and @maks 

This was originally broken because of a previous PR of mine - https://github.com/democloid/picoTracker/pull/92 - however that came about due to a change @maks wanted me to make - https://github.com/democloid/picoTracker/pull/92#discussion_r1461708746

I don't think its best to pop the loading line *back* where it was as then we're doubling up the settings when Status::Set gets called twice, once from `ImportSample` then `loadSample`...  However I've placed it where I believe it should be, and thats where the project is loading all the samples (i.e. `Load`).. this way `loadSample` can just focus on loading a sample into memory, the calling functions state the status of what they're doing making it a little more responsive for the user feedback.

The change in this PR is now one line and its clean enough for a merge.

**Comment by maks** [comment]
> I don't think its best to pop the loading line _back_ where it was as then we're doubling up the settings when Status::Set gets called twice, once from `ImportSample` then `loadSample`... However I've placed it where I believe it should be, and thats where the project is loading all the samples (i.e. `Load`).. this way `loadSample` can just focus on loading a sample into memory, the calling functions state the status of what they're doing making it a little more responsive for the user feedback.
> 
Thanks @shockdesign that makes sense. It looks good now and I'll try to test this out soon.

**Comment by maks** [comment]
ok looks good now, I think ready to merge 👍🏻

**Pull request merged**
