### PR TITLE
Make help legend less busy

### PR DESCRIPTION
**Pull request by djdiskmachine**
*Overwrite old text with spaces
*Nicer line breaks
*Corrected / added missing commands

### CODE REVIEW

**Review by maks — COMMENTED** [review]
Thanks for working more on this! 👍🏻 
One suggestion (just my personal preference) is perhaps to have some of the 2 line ones be distributed so that params are moslty on same (2nd) line.
eg.
```
FilterCuToff:aabb
cutoff bb at speed aa
```

Also I think for this one, apart from spacing across lines there is also still the 4 letter capitalisation vs the 3 used in picotracker, so this should be:
```
Filter&ReS:aabb
cutoff aa resonance bb
```

what do you think?

**Comment by maks** [comment]
I think you can still have just 2 assignments per command, I was just thinking to split the 2 lines strings in slightly different places.

**Comment by democloid** [comment]
I was thinking it would be ideal to do the help message to the side of the table/phrase number indicator, but honestly haven't checked if it would fit well.

Another option would be to replace the notes on the bottom of the screen (but leave the map intact), thoughts?

**Comment by djdiskmachine** [comment]
> I was thinking it would be ideal to do the help message to the side of the table/phrase number indicator, but honestly haven't checked if it would fit well.
> 
> Another option would be to replace the notes on the bottom of the screen (but leave the map intact), thoughts?

Going from the leftmost border makes the most sense to me, frees up the most amount of space to write too :)

**Comment by maks** [comment]
I think the top is good but bottom replacing the notes display makes alot of sense too as you'd never be using the notes display while entering FX commands, but really I'm happy with either.

**Review by democloid — APPROVED** [review]
I'll approve this to unblock it, but I reserve the right to move it down :)

**Pull request merged**
